### ISSUE TITLE
Initial bindings tracking issue

### ISSUE THREAD

**Issue by mersinvald** [rise-ui/raqm-rs#1]
- [x] raqm_create
 - [x] raqm_destroy
 - [x] ~raqm_reference~ Should be handled through Rust's (A)Rc pointers
 - [x] raqm_add_font_feature
 - [x] raqm_set_language
 - [x] raqm_set_par_direction
 - [x] raqm_set_text
 - [x] raqm_set_text_utf8
 - [x] raqm_set_freetype_face
 - [x] raqm_set_freetype_face_range
 - [x] raqm_set_freetype_load_flags
 - [x] raqm_layout
 - [x] raqm_get_glyphs
 - [x] raqm_index_to_position
 - [x] raqm_position_to_index
